name: PR - labels

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  pr-labeling:
    runs-on: ubuntu-latest

    steps:
    - name: first step
<<<<<<< Updated upstream
      run: echo "label status changed"
    - name: second step
      run: echo $ {{github.event.types.labels }}

=======
      run: echo "label status changed!!"
>>>>>>> Stashed changes
