name: Test Python and Docker

on:
  push:

jobs:
  linters:
    runs-on: ubuntu-latest
    
    steps:
    - name: Requirements
      run: |
        pip install -r ${{ github.workspace }}/code/requirements.txt
    - name: Run linters
      run: |
        flake8 code/python
    - name: Run security checks
      run: |
        bandit -r code/python




